# Generated by Django 5.1.4 on 2024-12-11 05:42

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                (
                    'middle_name',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    'gender',
                    models.CharField(
                        choices=[('male', 'Male'), ('female', 'Female')],
                        max_length=6,
                        null=True,
                    ),
                ),
                ('age', models.PositiveIntegerField(null=True)),
                ('nationality', models.CharField(max_length=50, null=True)),
                (
                    'friends',
                    models.ManyToManyField(blank=True, to='people.person'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='emails',
                        to='people.person',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(
                django.db.models.functions.text.Lower('last_name'),
                name='person_last_name_lower_idx',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'middle_name', 'last_name')},
        ),
    ]
